// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GrowthTracking.Repository.Models;

public partial class Consultation
{
    public Guid Id { get; set; }

    public DateOnly Day { get; set; }

    public TimeOnly Time { get; set; }

    public Guid UserId { get; set; }

    public Guid? DoctorId { get; set; }

    public DateTime CreationDate { get; set; }

    public Guid? CreatedBy { get; set; }

    public DateTime? ModificationDate { get; set; }

    public Guid? ModificationBy { get; set; }

    public DateTime? DeletionDate { get; set; }

    public Guid? DeleteBy { get; set; }

    public bool IsDeleted { get; set; }

    public virtual User User { get; set; }
}