// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GrowthTracking.Repository.Models;

public partial class User
{
    public Guid Id { get; set; }

    public string FullName { get; set; }

    public string Email { get; set; }

    public string PhoneNumber { get; set; }

    public string Password { get; set; }

    public bool IsVerified { get; set; }

    public string EmailToken { get; set; }

    public DateTime? VerifyAt { get; set; }

    public DateTime WorkDay { get; set; }

    public int RoleCodeId { get; set; }

    public DateTime CreationDate { get; set; }

    public Guid? CreatedBy { get; set; }

    public DateTime? ModificationDate { get; set; }

    public Guid? ModificationBy { get; set; }

    public DateTime? DeletionDate { get; set; }

    public Guid? DeleteBy { get; set; }

    public bool IsDeleted { get; set; }

    public DateTime? OtpExpiry { get; set; }

    public string VerifyOtp { get; set; }

    public virtual ICollection<Consultation> Consultations { get; set; } = new List<Consultation>();
}